;#define KERNEL_CODE_SELECTOR 0x08
;#define KERNEL_DATA_SELECTOR 0x10
;#define USER_CODE_SELECTOR 0x1B
;#define USER_DATA_SELECTOR 0x23

    KERNEL_CODE_SELECTOR equ 0x08
    KERNEL_DATA_SELECTOR equ 0x10
    USER_CODE_SELECTOR equ 0x1B
    USER_DATA_SELECTOR equ 0x23
    TSS_SELECTOR equ 0x28

